// models/ML.js

const { exec } = require('child_process');
const fs = require('fs');

// Function to run the trend analysis Python script
const runTrendAnalysis = () => {
    return new Promise((resolve, reject) => {
        exec('python scripts/trend_generator.py', (error, stdout, stderr) => {
            if (error) {
                console.error(`Error executing script: ${error.message}`);
                return reject(error);
            }

            if (stderr) {
                console.error(`Script error: ${stderr}`);
                return reject(stderr);
            }

            // Read the topics.csv file generated by the Python script
            fs.readFile('topics.txt', 'utf8', (err, data) => {
                if (err) {
                    console.error(`Error reading CSV file: ${err.message}`);
                    return reject(err);
                }

                // Convert CSV data to JSON
                const topics = data.split('\n\n'); // Adjust the separator based on your file structure

                // Extract words from each topic
                const result = topics.map((topic, index) => {
                    const words = topic.trim().split(', ');
                    return {
                        Topic: `Topic ${index}`,
                        Words: words,
                    };
                });
                resolve(result);
            });
        });
    });
};

module.exports = {
    runTrendAnalysis,
};
